# Generated by Django 4.1 on 2022-09-03 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sport', '0007_sport_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('court', models.ManyToManyField(to='Sport.court')),
                ('slot', models.ManyToManyField(to='Sport.timeslot')),
                ('sport', models.ManyToManyField(to='Sport.sport')),
            ],
        ),
    ]
