# Generated by Django 4.1 on 2022-09-03 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0007_sport_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='bookslot',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='bookslot',
            name='court',
        ),
        migrations.RemoveField(
            model_name='bookslot',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='bookslot',
            name='sport',
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.court')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='bookslot',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.court'),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.timeslot'),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.sport'),
        ),
    ]
