# Generated by Django 4.1 on 2022-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0002_court_sport_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='court',
            field=models.ManyToManyField(to='Sport.court'),
        ),
    ]
