# Generated by Django 4.1 on 2022-09-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0003_alter_sport_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='court',
        ),
        migrations.AddField(
            model_name='sport',
            name='court',
            field=models.CharField(choices=[], default='Unavailable', max_length=255),
        ),
    ]
